### ISSUE TITLE
autoloader issue when installing the framework

### ISSUE THREAD

**Issue by Sam-Mear** [tempestphp/tempest-framework#197] opened 2024-03-04 13:27 UTC
I have an existing codebase I was trying to move to tempest to test it out and i noticed on windows 10 wsl2 and on my other linux pop os laptop the command `./vendor/bin/tempest install` wont work after running composer require tempest-framework.

the error:

```
PHP Warning:  require_once(/home/some/directory/app/vendor/tempest/framework/vendor/autoload.php): Failed to open stream: No such file or directory in /home/some/directory/app/vendor/tempest/framework/tempest on line 10
PHP Warning:  require_once(/home/some/directory/app/../autoload.php): Failed to open stream: No such file or directory in /home/some/directory/app/vendor/tempest/framework/tempest on line 12
PHP Fatal error:  Uncaught Error: Failed opening required '/home/some/directory/app/../autoload.php' (include_path='.:/usr/share/php') in /home/some/directory/app/vendor/tempest/framework/tempest:12
Stack trace:
#0 /home/some/directory/app/vendor/bin/tempest(117): include()
#1 {main}
thrown in /home/some/directory/app/vendor/tempest/framework/tempest on line 12
```

looks like its adding the `../` into the directory rather than going up a level in the directory

**Comment by brendt** [comment] 2024-03-05 12:03
Are you running the command from your project root? What we're doing now is taking the current working directory, and assume it's the place where `vendor` lives in. So, running `./vendor/bin/tempest` is trying to find the autoloader here:

```php
require_once getcwd() . '/vendor/autoload.php';
```

Based on your paths, could it be that you're trying to run it while in the `app/` directory?

**Comment by Sam-Mear** [comment] 2024-03-05 13:51
Sorry i can see the confusion there, I named a folder app, cd into it, composer require then straight away tried `./vendor/bin/tempest` . i actually changed the directory there, ill post a more accurate one haha

ill try again and run through what i do. 
`cd ~`
`mkdir tempest-test`
`cd *test`
`composer init`(with all the defaults)
`composer require tempest/framework`
`./vendor/bin/tempest`

error:
```
PHP Warning:  require_once(/home/smear/tempest-test/vendor/tempest/framework/vendor/autoload.php): Failed to open stream: No such file or directory in /home/smear/tempest-test/vendor/tempest/framework/tempest on line 10
PHP Warning:  require_once(/home/smear/tempest-test/../autoload.php): Failed to open stream: No such file or directory in /home/smear/tempest-test/vendor/tempest/framework/tempest on line 12
PHP Fatal error:  Uncaught Error: Failed opening required '/home/smear/tempest-test/../autoload.php' (include_path='.:/usr/share/php') in /home/smear/tempest-test/vendor/tempest/framework/tempest:12
Stack trace:
#0 /home/smear/tempest-test/vendor/bin/tempest(117): include()
#1 {main}
  thrown in /home/smear/tempest-test/vendor/tempest/framework/tempest on line 12
```

**Comment by aidan-casey** [comment] 2024-03-05 14:12
@Sam-Mear - This will be fixed before v1, but I think while things are so fluid in our pre-release world, the instructions [here](https://github.com/tempestphp/tempest-app) are your best bet for playing around with Tempest in the meantime.

**Comment by yassiNebeL** [comment] 2024-03-05 14:50
I managed to reproduce this issue.

> Are you running the command from your project root? What we're doing now is taking the current working directory, and assume it's the place where `vendor` lives in. So, running `./vendor/bin/tempest` is trying to find the autoloader here:
> 
> ```
> require_once getcwd() . '/vendor/autoload.php';
> ```
> 
> Based on your paths, could it be that you're trying to run it while in the `app/` directory?

so `getcwd()` returns the tempest framework directory, which is actually inside the vendor folder, otherwise the error is thrown, so within the catch block it should be like so:

```php
try {
    require_once __DIR__ . '/autoload.php';
} catch (Throwable) {
    require_once getcwd() . '/../../autoload.php'; // exiting the tempest/framework dir, in order to meet the autoload file.
}
```
furthermore (for testing purpose), I tried to run `php -S localhost:8000 ./vendor/tempest/framework/public/index.php`, since the `public/index.php` file require the `vendor\autoload.php` an error thrown:

`/../vendor/autoload.php): Failed to open stream: No such file or directory in C:\Codes\OSS\testing\vendor\tempest\framework\public\index.php on line 7
`

**I replicated what Sam-Mear did.**

**Comment by brendt** [comment] 2024-03-06 04:37
What confuses me is that we have a CI testcase for this, and it works just fine: https://github.com/tempestphp/tempest-app/actions/runs/8154721322/job/22288725099

@Sam-Mear what's the output for `getcwd()`? You can head into the `vendor/bin/tempest` file and just do something like 

```php
var_dump(getcwd());
exit;
```

At the very top. Then run it from within your project's root.

**Comment by Sam-Mear** [comment] 2024-03-06 08:27
@brendt this was the output:
`~/tempest-test$ ./vendor/bin/tempest`
`string(24) "/home/smear/tempest-test"`

**Comment by yassiNebeL** [comment] 2024-03-06 17:03
@Sam-Mear let's fix this.

right now, `tempest` has the following code:

```php
try {
    require_once __DIR__ . '/autoload.php';
} catch (Throwable) {
    require_once getcwd() . '/autoload.php';
}
```

what if we replace the `try/catch` block to a sanity check: `if( file_exists('...') { require_once('...'); }`, of course we will use `realpath` and `getcwd`.

**Comment by brendt** [comment] 2024-03-07 04:29
@yassiNebeL you're wrong, on main tempest looks like this:

```
#!/usr/bin/env php
<?php

use Tempest\Tempest;

require_once getcwd() . '/vendor/autoload.php';

Tempest::boot(getcwd())->console()->run();

exit;
```

**Comment by brendt** [comment] 2024-03-07 04:29
@Sam-Mear could you share the contents of the file in `vendor/bin/tempest` ?

**Comment by Sam-Mear** [comment] 2024-03-07 09:07
sorry not been very helpful on my end, not had much time to look into it.

the error occurs not in vendor/bin/tempest, but in vendor/tempest/framework/tempest, where the file reads:
```php
#!/usr/bin/env php
<?php

use Tempest\AppConfig;
use Tempest\Application\Environment;
use Tempest\Tempest;
use function Tempest\env;

try {
    require_once __DIR__ . '/vendor/autoload.php';
} catch (Throwable) {
    require_once getcwd() . '/../autoload.php';
}

Tempest::setupEnv(__DIR__);

Tempest::boot(new AppConfig(
    appPath: __DIR__ . '/app',
    appNamespace: 'App\\',
    environment: Environment::from(env('ENVIRONMENT')),
    discoveryCache: env('DISCOVERY_CACHE'),
))->console()->run();

exit;
```

I had fixed it locally by changing `require_once getcwd() . '/../autoload.php';` to `require_once getcwd() . '/vendor/autoload.php';`

also to make it read the .env i had to place it in vendor/tempest/framework

looks like the code you put is in the current repository, but when you require tempest/framework it grabs ^0.0.4 which has an outdated file.

**Comment by brendt** [comment] 2024-03-07 10:21
Oh, you shouldn't use that file :) It's also an outdated version.

You should either use `./vendor/bin/tempest` or `./tempest`; the file in the vendor repo is only there to be copied by composer.

**Closed by brendt** 2024-03-07 10:21 UTC
Labels: bug

**Comment by Sam-Mear** [comment] 2024-03-07 10:41
Can confirm doing `composer require tempest/framework:dev-main` fixes this for now

(sorry if this reopens this issue from me responding, is not my intention)

**Comment by brendt** [comment] 2024-03-08 05:23
No problem! Thanks for confirming :)
