### ISSUE TITLE
[Bug]: Rector is broken

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#597] opened 2024-10-18 11:11 UTC
### Tempest Version

1.0-alpha2

### PHP Version

8.3

### Operating System

MacOS

### Description

Rector doesn't work

### Steps to Reproduce

Run rector locally

**Comment by brendt** [comment] 2024-10-18 11:15
See https://github.com/rectorphp/rector/issues/8864

**Comment by PierreThiollent** [comment] 2024-10-26 10:47
Hello,

I wanted to try to fix the bug but I can't reproduce it, Rector works correctly. The mentioned issue has been closed so I think we can close this one too 😊

**Comment by aidan-casey** [comment] 2024-10-26 13:34
Sorry, yes this can be closed. 🙂

**Closed** 2024-10-26 13:34 UTC
Labels: Bug, Stewardship
