### ISSUE TITLE
Add UploadCaster class

### ISSUE THREAD

**Issue by yassiNebeL** [tempestphp/tempest-framework#802] opened 2024-12-03 14:48 UTC
Let's add an UploadCaster class.

**Comment by yassiNebeL** [comment] 2024-12-06 17:12
Hey @innocenzi, I'll take care of this.

**Comment by innocenzi** [comment] 2024-12-06 17:19
You can re-open the pull request you closed about it.

**Comment by innocenzi** [comment] 2024-12-06 23:24
Duplicate of https://github.com/tempestphp/tempest-framework/issues/723

**Closed** 2024-12-06 23:24 UTC
Labels: Feature Request
